---
title: 'Project 2: Modeling, Testing, and Predicting'
author: "Renee Jones rlj2277 SDS348"
date: '11/22'
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
---

```{r setup, include=FALSE}
library(knitr)
hook_output = knit_hooks$get('output')
knit_hooks$set(output = function(x, options) {
  # this hook is used only when the linewidth option is not NULL
  if (!is.null(n <- options$linewidth)) {
    x = knitr:::split_lines(x)
    # any lines wider than n should be wrapped
    if (any(nchar(x) > n)) x = strwrap(x, width = n)
    x = paste(x, collapse = '\n')
  }
  hook_output(x, options)
})

knitr::opts_chunk$set(echo = TRUE, eval = TRUE,fig.align="center",warning=FALSE,message=FALSE,fig.width=8, fig.height=5, linewidth=60)
options(tibble.width = 100,width = 100)
library(tidyverse)
```

## 0. Introduction

```{R}
Melanoma <- read_csv("Melanoma.csv")
??Melanoma
Melanoma$sex[Melanoma$sex=="1"] <- "Male"
Melanoma$sex[Melanoma$sex=="0"] <- "Female"
Melanoma$status[Melanoma$status=="1"] <- "Dead"
Melanoma$status[Melanoma$status=="2"] <- "Alive"
Melanoma$status[Melanoma$status=="3"] <- "Other causes"
```

- The dataset Melanoma has 205 observations on patients in Denmark with malignant melanoma. There are 7 variables, 4 of which are numeric, 3 are categorical, and 2 of those 3 are binary. The variables include survival time measured in days, sex depicted as male(1) or female(0), age in years, the year of operation, tumor thickness in mm, and ulcer depicted as present(1) or absent(0). Also, status is another varible shown as a 1, 2, or 3. 1 indicates the patient died from melanoma, 2 indicates the patient is alive, and 3 indicates the patient died from other causes.

## 1. MANOVA

```{R}
man1<-manova(cbind(time,thickness)~sex, data=Melanoma)
summary(man1)
summary.aov(man1)
Melanoma%>%group_by(sex)%>%summarize(mean(time),mean(thickness))
pairwise.t.test(Melanoma$time, Melanoma$sex, p.adj="none")
pairwise.t.test(Melanoma$thickness, Melanoma$sex, p.adj="none")
.05/7
head(Melanoma)
```

- Survival time and/or tumour thickness show a mean difference across the sex of the patient. Because the p-value is less than the alpha for the MANOVA, for at least one of these response variables, at least one group mean differs. The univariate ANOVAs show that for both survival time and tumour thickness, at least one sex differs. I have performed 1 MANOVA, 2 ANOVAS, and 4 t tests, 7 in total. When unadjusted, the probability of at least one type I error is 0.05, or a 5% chance that rejecting the null hypothesis is wrong. The significance level should be adjusted using the bonferroni correction to be .0071. With this adjustment, there is no significant difference in survival time between females and males and no significant difference in tumour thickness between females and males. 

```{R}
library(rstatix)

group <- Melanoma$sex 
DVs <- Melanoma %>% select(time, thickness)

sapply(split(DVs,group), mshapiro_test)

box_m(DVs, group)

lapply(split(DVs,group), cov)
```

- The MANOVA assumptions of random samples, independent observations, linear relationships, no outliers, and no multicollinearity were most likely not met as it is very difficult to meet those assumptions. The multivariate normality assumption was violated for each group. Both females (p-value=2.693373e-15) and males (p-value=6.531259e-07) had p-values less than the alpha, so the null hypothesis is rejected. The Box's M-test shows a p-value of 0.3890951, so the assumption is met and there is homogeneity of within-group covariance matrices.  

## 2. Randomization Test

```{R}
ggplot(Melanoma,aes(time,fill=sex))+geom_histogram(bins=6.5)+ facet_wrap(~sex,ncol=2)+theme(legend.position="none")

Melanoma%>%group_by(sex)%>%
  summarize(means=mean(time))%>%summarize(`mean_diff`=diff(means))

rand_dist<-vector()

for(i in 1:5000){
new<-data.frame(time=sample(Melanoma$time),sex=Melanoma$sex)
rand_dist[i]<-mean(new[new$sex=="Male",]$time)-   
              mean(new[new$sex=="Female",]$time)
} 

{hist(rand_dist,main="",ylab=""); abline(v = c(-336.934, 336.934),col="red")}

mean(rand_dist>336.934 | rand_dist < -336.934)
```

- The null hypothesis is that the survival time is the same for patients of different sexes. The alternative hypothesis is that survival time is different for patients that are male vs. patients that are female. After doing a randomization test, we can reject the null hypothesis (p-value=0.0386<alpha=0.05) as there is a significant difference between the survival times of males and females. There is a 3.86% chance of observing a mean difference as extreme as the one under this randomization distribution. 

## 3. Linear Regression Model

```{R}
Melanoma$time_c <- Melanoma$time - mean(Melanoma$time, na.rm = T)
Melanoma$thickness_c <- Melanoma$thickness - mean(Melanoma$thickness, na.rm = T)
fit<-lm(time_c~thickness_c*ulcer, data=Melanoma)
summary(fit)
```

- The predicted value of survival time when both thickness is zero and an ulcer is absent is 255.025 days. While controlling for ulcer, for every 1 mm increase in thickness, survival time decreases by 6.441 days (not significant, t=-0.140, df=201, p=0.88883). While controlling for thickness, when an ulcer is present, survival time decreases by 467.110 days (significant, t=-2.793, df=201, p=0.00573). The slope for tumor thickness on survival time is 80.326 less for patients that have an ulcer present than those that do not (not significant, t=-1.383, df=201, p=0.16810).

```{R}
ggplot(Melanoma, aes(x=thickness_c,y=time_c,group=ulcer))+geom_point(aes(color=ulcer))+ geom_smooth(method="lm",formula=y~1,se=F,fullrange=T,aes(color=ulcer))+theme(legend.position=c(.9,.19))+xlab("")

ggplot(Melanoma, aes(thickness_c,time_c, color = ulcer)) + geom_smooth(method = "lm")+ geom_point()

resids<-lm(time_c~thickness_c*ulcer, data=Melanoma)$residuals
ggplot()+geom_histogram(aes(resids),bins=10)
fitted<-lm(time_c~thickness_c*ulcer, data=Melanoma)$fitted.values
ggplot()+geom_point(aes(fitted,resids))
resids<-fit$residuals
fitvals<-fit$fitted.values
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0, color='red')
ggplot(Melanoma, aes(thickness_c, time_c)) +geom_point(alpha=.3)
ggplot(Melanoma, aes(ulcer, time_c)) +geom_point(alpha=.3)
```

- The histogram of residuals looks normal, but the variance of the plot of residuals vs. fitted values does not look constant. The plot of thickness against ulcer doesn't show linearity and there is a fanning of points which indicates that the population is not homoskedastic.

```{R}
library(sandwich)
library(lmtest)
summary(fit)$coef
coeftest(fit, vcov=vcovHC(fit))
```

- The corrected robust standard errors show no change from before. There was no significant effect for tumour thickness on survival time while controlling for the presence of an ulcer. There was also no significant effect between the interaction of tumour thickness and ulcer on survival time. However, there was still a significant effect of whether an ulcer was present on survival time while controlling for tumour thickness. 
    
- Looking at the adjusted R-squared value, the model explains 0.08368 or 8.368% of the variation in the outcome. 

## 4. Linear Regression Model Cont'd

```{R}
fit<-lm(time_c~thickness_c*ulcer, data=Melanoma)
summary(fit)
resid_resamp<-replicate(5000,{
  new_resids<-sample(resids,replace=TRUE)
  Melanoma$new_y<-fitted+new_resids 
  fit<-lm(new_y~thickness_c*ulcer,data=Melanoma)
  coef(fit)
})
resid_resamp%>%t%>%as.data.frame%>%summarize_all(sd)
```

- Using bootstrapped standard errors, there are changes compared the original SEs and the robust SEs. The intercept went from original SE of 112.40411 to robust SE of 124.0606 to bootstrapped SE of 113.9085. Thickness went from an original SE of 46.02201 to robust SE of 54.5030 to bootstrapped SE of 45.83745. Ulcer went from an original SE of 167.23923 to a robust SE of 174.9145 to a bootstrapped SE of 167.9311. Finally, the interaction of thickness and ulcer had an original SE of 58.06792, a robust SE of 68.2294, and a bootstrapped SE of 57.07113. Any increase in standard error indicates an increase in p-value and any decrease in standard error indicates a decrease in p-value.  

## 5. Logistic Regression Model

```{R}
fit1<-glm(ulcer~time+thickness, data = Melanoma, family = "binomial")
coeftest(fit1)
exp(coef(fit1))
```

- While controlling for survival time and tumor thickness, the presence of an ulcer decreases by 0.547 in the patients. For every day increase in survival time, the presence of an ulcer decreases by .0004, while controlling for tumor thickness. For every mm increase in tumor thickness, the presence of an ulcer in a patient increases by 0.429, while controlling for survival time. 

```{R}
prob<-predict(fit1,type="response")
pred<-ifelse(prob>.5,1,0)
table(prediction=pred, truth=Melanoma$ulcer)%>%addmargins
(100+53)/205
53/90
100/115
53/68
```

- The accuracy is 0.7463415, the sensitivity or true positive rate is 0.5888889, the specificity or true negative rate is 0.8695652, and the precision is 0.7794118. 

```{R}
library(plotROC)
ROCplot1<-ggplot(Melanoma)+geom_roc(aes(d=ulcer,m=prob), n.cuts=0) 
ROCplot1
calc_auc(ROCplot1)
```

- From the ROC curve we can visualize the trade-off between sensitivity and specificity. The curve also gives the model an AUC of 0.8171014 which is pretty good.

```{R}
Melanoma$logit<-predict(fit1,type="link")
Melanoma$ulcer<-as.factor(Melanoma$ulcer)
Melanoma%>%ggplot()+geom_density(aes(logit,color=ulcer,fill=ulcer), alpha=.4)+
  theme(legend.position=c(.85,.85))+geom_vline(xintercept=0)+xlab("predictor (logit)")
```

## 6. Logistic Regression Model Cont'd

```{R}
class_diag<-function(probs,truth){
  tab<-table(factor(probs>.5,levels=c("FALSE","TRUE")),truth)
  acc=sum(diag(tab))/sum(tab)
  sens=tab[2,2]/colSums(tab)[2]
  spec=tab[1,1]/colSums(tab)[1]
  ppv=tab[2,2]/rowSums(tab)[2]
  f1=2*(sens*ppv)/(sens+ppv)

  if(is.numeric(truth)==FALSE & is.logical(truth)==FALSE){
    truth<-as.numeric(truth)-1}
  
  
  ord<-order(probs, decreasing=TRUE)
  probs <- probs[ord]; truth <- truth[ord]
  
  TPR=cumsum(truth)/max(1,sum(truth)) 
  FPR=cumsum(!truth)/max(1,sum(!truth))
  
  dup<-c(probs[-1]>=probs[-length(probs)], FALSE)
  TPR<-c(0,TPR[!dup],1); FPR<-c(0,FPR[!dup],1)
  
  n <- length(TPR)
  auc<- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )

  data.frame(acc,sens,spec,ppv,f1,auc)
}

fit2<-glm(ulcer~., data=Melanoma, family="binomial")
probs<-predict(fit2,type="response") 
class_diag(probs,Melanoma$ulcer)
```

- The accuracy of this model predicting whether or not a patient has an ulcer from all of the rest of the variables is 0.7658537. The sensitivity is 0.6666667, the specificity is 0.8434783, and the precision is 0.7692308. Finally, the AUC is 0.8154589 which is still pretty good. 

```{R}
set.seed(1234) 
k=10

data <- Melanoma %>% sample_frac
folds <- ntile(1:nrow(data),n=10)

diags<-NULL 
for(i in 1:k){
  train <- data[folds!=i,]  
  test <- data[folds==i,] 
  
  truth <- test$ulcer 
  
  fit2 <- glm(ulcer~., data=train, family="binomial") 
  probs <- predict(fit2, newdata=test, type="response")
  
  diags<-rbind(diags,class_diag(probs,truth)) 
}

summarize_all(diags,mean)
```

- After performing 10-fold cross validation with the same model, the following average out-of-sample classification diagnostics were observed. The accuracy is 0.7461905, the sensitivity is 0.6658458, the specificity is 0.8238603, and the precision is 0.7571248. The AUC is 0.7884466 which is fair, but it dropped from the in-sample metrics which indicates lots of overfitting.

```{R}
library(glmnet)
Melanoma$status <- factor(Melanoma$status)
Melanoma$sex <- factor(Melanoma$sex)
y<-as.matrix(Melanoma$ulcer)
x<-model.matrix(ulcer~.,data=Melanoma)[,-1] 
head(x)
cv <- cv.glmnet(x,y, family="binomial")
lasso<-glmnet(x,y,family="binomial",lambda=cv$lambda.1se)
coef(lasso)
```

- After performing LASSO on the same model and variables, the most predictive variable was status of dying from melanoma.

```{R}
set.seed(1234) 
k=10

Melanoma<-Melanoma %>% mutate(statusDead=ifelse(Melanoma$status=="Dead",1,0))

data <- Melanoma %>% sample_frac
folds <- ntile(1:nrow(data),n=10)

diags<-NULL 
for(i in 1:k){
  train <- data[folds!=i,]  
  test <- data[folds==i,] 
  
  truth <- test$ulcer 
  
  fit3 <- glm(ulcer~statusDead, data=train,family="binomial") 
  probs <- predict(fit3, newdata=test, type="response")
  
  diags<-rbind(diags,class_diag(probs,truth)) 
}

summarize_all(diags,mean)
```

- This 10-fold CV using only statusDead, the variable lasso selected shows a big change in predicting the presence of an ulcer in a patient. The model's out-of-sample AUC is 0.6621093 which is poor and much lower than the previous AUCs of the logistic regressions. Therefore, the original model was overfitting by a lot.

...





